# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d4a2c356b183388865830a42ae05ef986573acd035cef34d2ad211f7ec740800915b6ffd939e812138a5b43888ce350a31ee26bc0cf80f3f6ddbabb0627af5d

test:
  secret_key_base: ed32eb3c6d1000033358d3fff882d43de9fd89df5e4d670c4152a7b802e3688b4fb96d74624be3d4097f8ad3b0fa366b9103c327ef8d853806d8a8928427ce8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
